"""empty message

Revision ID: 00260e0e9dd0
Revises: db051f1eba74
Create Date: 2024-04-30 11:16:39.699749

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '00260e0e9dd0'
down_revision = 'db051f1eba74'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('animals', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('user_email')

    with op.batch_alter_table('crops', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('user_email')

    with op.batch_alter_table('fruits', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('user_email')

    with op.batch_alter_table('profiles', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('user_email')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('profiles', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_email', sa.VARCHAR(length=100), nullable=True))
        batch_op.create_foreign_key(None, 'users', ['user_email'], ['email'])

    with op.batch_alter_table('fruits', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_email', sa.VARCHAR(length=100), nullable=True))
        batch_op.create_foreign_key(None, 'users', ['user_email'], ['email'])

    with op.batch_alter_table('crops', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_email', sa.VARCHAR(length=100), nullable=True))
        batch_op.create_foreign_key(None, 'users', ['user_email'], ['email'])

    with op.batch_alter_table('animals', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_email', sa.VARCHAR(length=100), nullable=True))
        batch_op.create_foreign_key(None, 'users', ['user_email'], ['email'])

    # ### end Alembic commands ###
