"""Crops table

Revision ID: 830cb087a350
Revises: 8f00397334f2
Create Date: 2024-04-01 20:08:11.098967

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '830cb087a350'
down_revision = '8f00397334f2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('crops',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=True),
    sa.Column('descripton', sa.Text(length=500), nullable=True),
    sa.Column('user_email', sa.String(length=100), nullable=True),
    sa.Column('number', sa.Integer(), nullable=True),
    sa.Column('price', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_email'], ['users.email'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('crops')
    # ### end Alembic commands ###
